#!/usr/bin/python

import networkx as nx



def main(dfgfile, aafile):
    DFG = nx.DiGraph(nx.drawing.nx_agraph.read_dot(dfgfile))
    assert nx.algorithms.is_directed_acyclic_graph(DFG) 


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
